version: '3.4'

services:
  interface:
    image: beademingstoestel/interface
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      args:
        environment: test
    ports:
      - 3001:3001
    depends_on:
      - mongo
    restart: always  
  mongo:
    image: beademingstoestel/mongo
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    restart: always
    environment:
      MONGO_INITDB_DATABASE: beademing
    ports:
      - 27017:27017
    volumes:
      - ./docker/db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
